In [8]:
import torch

In [17]:
x = torch.randint(0, 10, (2, 3, 4))

In [18]:
x

tensor([[[9, 8, 6, 9],
         [8, 0, 1, 1],
         [0, 5, 5, 0]],

        [[7, 2, 4, 2],
         [1, 0, 1, 5],
         [2, 9, 1, 7]]])

In [19]:
y = x.view(2, -1)

In [20]:
y

tensor([[9, 8, 6, 9, 8, 0, 1, 1, 0, 5, 5, 0],
        [7, 2, 4, 2, 1, 0, 1, 5, 2, 9, 1, 7]])

In [21]:
z = y.unsqueeze(0)

In [22]:
z

tensor([[[9, 8, 6, 9, 8, 0, 1, 1, 0, 5, 5, 0],
         [7, 2, 4, 2, 1, 0, 1, 5, 2, 9, 1, 7]]])

In [27]:
z.squeeze(0)

tensor([[9, 8, 6, 9, 8, 0, 1, 1, 0, 5, 5, 0],
        [7, 2, 4, 2, 1, 0, 1, 5, 2, 9, 1, 7]])

In [28]:
x = torch.randint(10, (3, 4, 2))

In [29]:
x

tensor([[[6, 8],
         [9, 1],
         [2, 9],
         [5, 1]],

        [[7, 9],
         [1, 7],
         [6, 4],
         [6, 7]],

        [[7, 3],
         [2, 0],
         [8, 0],
         [4, 4]]])

In [36]:
y = torch.max(x, dim=0)

In [37]:
y

torch.return_types.max(
values=tensor([[7, 9],
        [9, 7],
        [8, 9],
        [6, 7]]),
indices=tensor([[1, 1],
        [0, 1],
        [2, 0],
        [1, 1]]))

In [38]:
z = torch.max(x, dim=1)

In [39]:
z

torch.return_types.max(
values=tensor([[9, 9],
        [7, 9],
        [8, 4]]),
indices=tensor([[1, 2],
        [0, 0],
        [2, 3]]))